services:

  db:
    image: postgres:16
    container_name: food-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - food_orders_data:/var/lib/postgresql/data
    networks:
      - food-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  order-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: food-order-api
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PORT: ${API_PORT}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - food-network

  nginx:
    image: nginx:alpine
    container_name: food-nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - order-api
    networks:
      - food-network

volumes:
  food_orders_data:

networks:
  food-network:
    driver: bridge